export const papersStub = [
	{
		_id: '5f1ff663114dcd2cc53e5ece',
		id: 32300742,
		activeflag: 'active',
		authors: [100000],
		counter: 8,
		createdAt: '2021-02-14T02:02:04.237Z',
		datasetids: [],
		description:
			'\n\n**Lay Summary**\n\nBackground:The incidence of knife-related injuries is rising across the UK. This study aimed to determine the spectrum of knife-related injuries in a major UK city, with regards to patient and injury characteristics. A secondary aim was to quantify their impact on secondary care resources. Methods:Observational study of patients aged 16+ years admitted to a major trauma centre following knife-related injuries resulting from interpersonal violence (May 2015 to April 2018). Patients were identified using Emergency Department and discharge coding, blood bank and UK national Trauma Audit and Research prospective registries. Patient and injury characteristics, outcome and resource utilisation were collected from ambulance and hospital records. Findings:532 patients were identified; 93% male, median age 26 years (IQR 20-35). Median injury severity score was 9 (IQR 3-13). 346 (65%) underwent surgery; 133 (25%) required intensive care; 95 (17·9%) received blood transfusion. Median length of stay was 3·3 days (IQR 1·7-6·0). In-hospital mortality was 10/532 (1·9%). 98 patients (18·5%) had previous attendance with violence-related injuries. 24/37 females (64·9%) were injured in a domestic setting. Intoxication with alcohol (19·2%) and illicit drugs (17·6%) was common. Causative weapon was household knife in 9%, knife (other/unspecified) in 38·0%, machete in 13·9%, small folding blade (2·8%) and, unrecorded in 36·3%. Interpretation:Knife injuries constitute 12·9% of trauma team workload. Violence recidivism and intoxication are common, and females are predominantly injured in a domestic setting, presenting opportunities for targeted violence reduction interventions. 13·9% of injuries involved machetes, with implications for law enforcement strategies.\n\n\n\n**Authors:**\n\nMalik NS, Munoz B, de Courcey C, Imran R, Lee KC, Chernbumroong S, Bishop J, Lord JM, Gkoutos G, Bowley DM, Foster MA.\n\n',
		journal: 'EClinicalMedicine',
		journalYear: 2020,
		link: 'https://doi.org/10.1016/j.eclinm.2020.100296',
		name: 'Violence-related knife injuries in a UK city; epidemiology and impact on secondary care resources.',
		relatedObjects: [],
		source_url: 'https://raw.githubusercontent.com/HDRUK/papers/master/data/papers.csv',
		tags: {
			features: ['HDRUK Papers', 'Open Access'],
			topics: [],
		},
		toolids: [],
		type: 'paper',
		updatedAt: '2021-02-14T02:02:04.237Z',
		updatedon: '2021-02-14T02:02:04.237Z',
		document_links: [
			{
				doi: 'https://doi.org/10.1016/j.eclinm.2020.100296',
			},
			{
				html: 'https://europepmc.org/articles/PMC7152819',
			},
			{
				pdf: 'https://europepmc.org/articles/PMC7152819?pdf=render',
			},
		],
		persons: [
			{
				_id: '5f1ff1e0114dcd2cc53e1e90',
				id: 100000,
				activeflag: 'active',
				usedids: [],
				projectids: [],
				sociallinks: [''],
				datasetids: [],
				linkedids: [],
				firstname: 'HDR UK',
				type: 'person',
				lastname: 'Papers Team',
				tags: [],
				updatedon: '2020-05-21T00:00:00.001Z',
				bio: '',
				counter: 38,
				updatedAt: '2021-01-27T21:08:18.164Z',
				organisation: '',
				sector: '',
				domain: '',
				link: '',
				orcid: '',
			},
		],
		objects: [],
		reviews: [],
	},
	{
		_id: '5f1ff69f114dcd2cc53e6288',
		id: 32276644,
		activeflag: 'active',
		authors: [100000],
		counter: 6,
		createdAt: '2021-02-14T02:02:04.237Z',
		datasetids: [],
		description:
			"\n\n**Lay Summary**\n\nBACKGROUND:Inaccurately modelled environmental exposures may have important implications for evidence-based policy targeting health promoting or hazardous facilities. Travel routes modelled using GIS generally use shortest network distances or Euclidean buffers to represent journeys with corresponding built-environment exposures calculated along these routes. These methods, however, are an unreliable proxy for calculating child built-environment exposures as child route choice is more complex than shortest network routes. METHODS:We hypothesised that a GIS model informed by characteristics of the built-environment known to influence child route choice could be developed to more accurately model exposures. Using GPS-derived walking commutes to and from school we used logistic regression models to highlight built-environment features important in child route choice (e.g. road type, traffic light count). We then recalculated walking commute routes using a weighted network to incorporate built-environment features. Multilevel regression analyses were used to validate exposure predictions to the retail food environment along the different routing methods. RESULTS:Children chose routes with more traffic lights and residential roads compared to the modelled shortest network routes. Compared to standard shortest network routes, the GPS-informed weighted network enabled GIS-based walking commutes to be derived with more than three times greater accuracy (38%) for the route to school and more than 12 times greater accuracy (92%) for the route home. CONCLUSIONS:This research advocates using weighted GIS networks to accurately reflect child walking journeys to school. The improved accuracy in route modelling has in turn improved estimates of children's exposures to potentially hazardous features in the environment. Further research is needed to explore if the built-environment features are important internationally. Route and corresponding exposure estimates can be scaled to the population level which will contribute to a better understanding of built-environment exposures on child health and contribute to mobility-based child health policy.\n\n\n\n**Authors:**\n\nMizen A, Fry R, Rodgers S.\n\n",
		journal: 'International journal of health geographics',
		journalYear: 2020,
		link: 'https://doi.org/10.1186/s12942-020-00208-2',
		name: 'GIS-modelled built-environment exposures reflecting daily mobility for applications in child health research.',
		relatedObjects: [],
		source_url: 'https://raw.githubusercontent.com/HDRUK/papers/master/data/papers.csv',
		tags: {
			features: [
				'HDRUK Papers',
				'Open Access',
				'Environmental exposure',
				'Child Health',
				'Walking',
				'Weighted Network',
				'Daily Mobility',
				'School Commute',
			],
			topics: [],
		},
		toolids: [],
		type: 'paper',
		updatedAt: '2021-02-14T02:02:04.237Z',
		updatedon: '2021-02-14T02:02:04.237Z',
		document_links: [
			{
				doi: 'https://doi.org/10.1186/s12942-020-00208-2',
			},
			{
				html: 'https://europepmc.org/articles/PMC7147039',
			},
			{
				pdf: 'https://europepmc.org/articles/PMC7147039?pdf=render',
			},
		],
		persons: [
			{
				_id: '5f1ff1e0114dcd2cc53e1e90',
				id: 100000,
				activeflag: 'active',
				usedids: [],
				projectids: [],
				sociallinks: [''],
				datasetids: [],
				linkedids: [],
				firstname: 'HDR UK',
				type: 'person',
				lastname: 'Papers Team',
				tags: [],
				updatedon: '2020-05-21T00:00:00.001Z',
				bio: '',
				counter: 38,
				updatedAt: '2021-01-27T21:08:18.164Z',
				organisation: '',
				sector: '',
				domain: '',
				link: '',
				orcid: '',
			},
		],
		objects: [],
		reviews: [],
	},
	{
		_id: '5f1ff69f114dcd2cc53e6293',
		id: 32405103,
		activeflag: 'active',
		authors: [100000],
		counter: 2,
		createdAt: '2021-02-14T02:02:04.237Z',
		datasetids: [],
		description:
			'\n\n**Lay Summary**\n\n<h4>Background</h4>The medical, societal, and economic impact of the coronavirus disease 2019 (COVID-19) pandemic has unknown effects on overall population mortality. Previous models of population mortality are based on death over days among infected people, nearly all of whom thus far have underlying conditions. Models have not incorporated information on high-risk conditions or their longer-term baseline (pre-COVID-19) mortality. We estimated the excess number of deaths over 1 year under different COVID-19 incidence scenarios based on varying levels of transmission suppression and differing mortality impacts based on different relative risks for the disease.<h4>Methods</h4>In this population-based cohort study, we used linked primary and secondary care electronic health records from England (Health Data Research UK-CALIBER). We report prevalence of underlying conditions defined by Public Health England guidelines (from March 16, 2020) in individuals aged 30 years or older registered with a practice between 1997 and 2017, using validated, openly available phenotypes for each condition. We estimated 1-year mortality in each condition, developing simple models (and a tool for calculation) of excess COVID-19-related deaths, assuming relative impact (as relative risks [RRs]) of the COVID-19 pandemic (compared with background mortality) of 1·5, 2·0, and 3·0 at differing infection rate scenarios, including full suppression (0·001%), partial suppression (1%), mitigation (10%), and do nothing (80%). We also developed an online, public, prototype risk calculator for excess death estimation.<h4>Findings</h4>We included 3 862 012 individuals (1 957 935 [50·7%] women and 1 904 077 [49·3%] men). We estimated that more than 20% of the study population are in the high-risk category, of whom 13·7% were older than 70 years and 6·3% were aged 70 years or younger with at least one underlying condition. 1-year mortality in the high-risk population was estimated to be 4·46% (95% CI 4·41-4·51). Age and underlying conditions combined to influence background risk, varying markedly across conditions. In a full suppression scenario in the UK population, we estimated that there would be two excess deaths (vs baseline deaths) with an RR of 1·5, four with an RR of 2·0, and seven with an RR of 3·0. In a mitigation scenario, we estimated 18 374 excess deaths with an RR of 1·5, 36 749 with an RR of 2·0, and 73 498 with an RR of 3·0. In a do nothing scenario, we estimated 146 996 excess deaths with an RR of 1·5, 293 991 with an RR of 2·0, and 587 982 with an RR of 3·0.<h4>Interpretation</h4>We provide policy makers, researchers, and the public a simple model and an online tool for understanding excess mortality over 1 year from the COVID-19 pandemic, based on age, sex, and underlying condition-specific estimates. These results signal the need for sustained stringent suppression measures as well as sustained efforts to target those at highest risk because of underlying conditions with a range of preventive interventions. Countries should assess the overall (direct and indirect) effects of the pandemic on excess mortality.<h4>Funding</h4>National Institute for Health Research University College London Hospitals Biomedical Research Centre, Health Data Research UK.\n\n\n\n**Authors:**\n\nBanerjee A, Pasea L, Harris S, Gonzalez-Izquierdo A, Torralbo A, Shallcross L, Noursadeghi M, Pillay D, Sebire N, Holmes C, Pagel C, Wong WK, Langenberg C, Williams B, Denaxas S, Hemingway H.\n\n',
		journal: 'Lancet (London, England)',
		journalYear: 2020,
		link: 'https://doi.org/10.1016/s0140-6736(20)30854-0',
		name:
			'Estimating excess 1-year mortality associated with the COVID-19 pandemic according to underlying conditions and age: a population-based cohort study.',
		relatedObjects: [],
		source_url: 'https://raw.githubusercontent.com/HDRUK/papers/master/data/papers.csv',
		tags: {
			features: ['HDRUK Papers', 'Open Access'],
			topics: [],
		},
		toolids: [],
		type: 'paper',
		updatedAt: '2021-02-14T02:02:04.237Z',
		updatedon: '2021-02-14T02:02:04.237Z',
		document_links: [
			{
				doi: 'https://doi.org/10.1016/S0140-6736(20)30854-0',
			},
			{
				html: 'https://europepmc.org/articles/PMC7217641',
			},
		],
		persons: [
			{
				_id: '5f1ff1e0114dcd2cc53e1e90',
				id: 100000,
				activeflag: 'active',
				usedids: [],
				projectids: [],
				sociallinks: [''],
				datasetids: [],
				linkedids: [],
				firstname: 'HDR UK',
				type: 'person',
				lastname: 'Papers Team',
				tags: [],
				updatedon: '2020-05-21T00:00:00.001Z',
				bio: '',
				counter: 38,
				updatedAt: '2021-01-27T21:08:18.164Z',
				organisation: '',
				sector: '',
				domain: '',
				link: '',
				orcid: '',
			},
		],
		objects: [],
		reviews: [],
	},
	{
		_id: '5f1ff69f114dcd2cc53e629e',
		id: 32499256,
		activeflag: 'active',
		authors: [100000],
		counter: 3,
		createdAt: '2021-02-14T02:02:04.237Z',
		datasetids: [],
		description:
			'\n\n**Lay Summary**\n\nINTRODUCTION:Urinary tract infections (UTIs) are the second most common type of infection worldwide, accounting for a large number of primary care consultations and antibiotic prescribing. Current diagnosis is based on an empirical approach, relying on symptoms and occasional use of urine dipsticks. The diagnostic reference standard is still urine culture, although it is not routinely recommended for uncomplicated UTIs in the community, due to time to diagnosis (48 hours). Faster point-of-care tests have been developed, but their diagnostic accuracy has not been compared. Our objective is to systematically review and meta-analyse the diagnostic accuracy of currently available point-of-care tests for UTIs. METHODS AND ANALYSIS:Studies evaluating the diagnostic accuracy of point-of-care tests for UTIs will be included. PubMed, Web of Science, Embase and Cochrane Database of Systematic Reviews were searched from inception to 1 June 2019. Data extraction and risk-of-bias assessment will be assessed using the Quality Assessment of Diagnostic Accuracy Studies tool. Meta-analysis will be performed depending on data availability and heterogeneity. ETHICS AND DISSEMINATION:This is a systematic review protocol and therefore formal ethical approval is not required, as no primary, identifiable, personal data will be collected. Patients or the public were not involved in the design of our research. However, the findings from this review will be shared with key stakeholders, including patient groups, clinicians and guideline developers, and will also be presented and national and international conferences. PROSPERO REGISTRATION NUMBER:CRD42018112019.\n\n\n\n**Authors:**\n\nFraile Navarro D, Sullivan F, Azcoaga-Lorenzo A, Hernandez Santiago V.\n\n',
		journal: 'BMJ open',
		journalYear: 2020,
		link: 'https://doi.org/10.1136/bmjopen-2019-033424',
		name:
			'Point-of-care tests for urinary tract infections: protocol for a systematic review and meta-analysis of diagnostic test accuracy.',
		relatedObjects: [],
		source_url: 'https://raw.githubusercontent.com/HDRUK/papers/master/data/papers.csv',
		tags: {
			features: [
				'HDRUK Papers',
				'Open Access',
				'Urinary tract infections',
				'epidemiology',
				'Molecular Diagnostics',
				'Diagnostic Microbiology',
			],
			topics: [],
		},
		toolids: [],
		type: 'paper',
		updatedAt: '2021-02-14T02:02:04.237Z',
		updatedon: '2021-02-14T02:02:04.237Z',
		document_links: [
			{
				doi: 'https://doi.org/10.1136/bmjopen-2019-033424',
			},
			{
				html: 'https://europepmc.org/articles/PMC7282288',
			},
			{
				pdf: 'https://europepmc.org/articles/PMC7282288?pdf=render',
			},
		],
		persons: [
			{
				_id: '5f1ff1e0114dcd2cc53e1e90',
				id: 100000,
				activeflag: 'active',
				usedids: [],
				projectids: [],
				sociallinks: [''],
				datasetids: [],
				linkedids: [],
				firstname: 'HDR UK',
				type: 'person',
				lastname: 'Papers Team',
				tags: [],
				updatedon: '2020-05-21T00:00:00.001Z',
				bio: '',
				counter: 38,
				updatedAt: '2021-01-27T21:08:18.164Z',
				organisation: '',
				sector: '',
				domain: '',
				link: '',
				orcid: '',
			},
		],
		objects: [],
		reviews: [],
	},
];
