export const coursesStub = [
	{
		_id: '602427a273d8765aeb89f87b',
		id: 50033,
		activeflag: 'active',
		award: [],
		competencyFramework: '',
		counter: 5,
		courseDelivery: 'campus',
		courseOptions: [
			{
				flexibleDates: true,
				startDate: null,
				studyMode: '',
				studyDurationNumber: null,
				studyDurationMeasure: '',
				fees: [
					{
						feeDescription: '',
						feeAmount: null,
						feePer: '',
					},
				],
			},
		],
		createdAt: '2021-02-10T18:36:18.463Z',
		creator: 50000,
		description:
			'Health data analytics involves extracting insights from health data, either to shape national policy, manage local organisations or inform the care of an individual. As more and more data becomes available electronically, the demand for skilled and trained individuals to take advantage of it becomes increasingly urgent.',
		domains: ['Course'],
		entries: [
			{
				level: '',
				subject: '',
			},
		],
		keywords: [],
		link: 'https://www.ucl.ac.uk/health-informatics/study/postgraduate-taught-programmes/health-data-analytics-mscpg-dippg-cert',
		location: 'London',
		nationalPriority: '',
		provider: 'UCL Institute of Health Informatics',
		relatedObjects: [],
		restrictions: 'other:Relevant first degree or equivalent experience required',
		title: 'Health Data Analytics',
		type: 'course',
		updatedAt: '2021-02-12T17:33:14.501Z',
		persons: [],
		objects: [],
		reviews: [],
	},
	{
		_id: '602427a273d8765aeb89f7cb',
		id: 50017,
		activeflag: 'active',
		award: [],
		competencyFramework: '',
		counter: 4,
		courseDelivery: 'campus',
		courseOptions: [
			{
				flexibleDates: true,
				startDate: null,
				studyMode: '',
				studyDurationNumber: null,
				studyDurationMeasure: '',
				fees: [
					{
						feeDescription: '',
						feeAmount: null,
						feePer: '',
					},
				],
			},
		],
		createdAt: '2021-02-10T18:36:18.463Z',
		creator: 50000,
		description:
			'The aim of this course is to familiarize the participants with the primary analysis of RNA-seq data.\n\nThis course starts with a brief introduction to RNA-seq and discusses quality control issues. Next, we will present the alignment step, quantification of expression and differential expression analysis. For downstream analysis we will focus on tools available through the Bioconductor project for manipulating and analysing bulk RNA-seq.',
		domains: ['Course'],
		entries: [
			{
				level: '',
				subject: '',
			},
		],
		keywords: [],
		link: 'https://training.csx.cam.ac.uk/bioinformatics/course/bioinfo-RNAseq3',
		location: 'Cambridge',
		nationalPriority: '',
		provider: 'University of Cambridge',
		relatedObjects: [],
		restrictions: 'Course prerequisites apply',
		title: 'Introduction to RNA-seq data analysis',
		type: 'course',
		updatedAt: '2021-02-12T15:20:08.869Z',
		persons: [],
		objects: [],
		reviews: [],
	},
	{
		_id: '602427a373d8765aeb89fa5f',
		id: 50077,
		activeflag: 'active',
		award: [],
		competencyFramework: '',
		counter: 2,
		courseDelivery: 'campus',
		courseOptions: [
			{
				flexibleDates: true,
				startDate: null,
				studyMode: '',
				studyDurationNumber: null,
				studyDurationMeasure: '',
				fees: [
					{
						feeDescription: '',
						feeAmount: null,
						feePer: '',
					},
				],
			},
		],
		createdAt: '2021-02-10T18:36:18.463Z',
		creator: 50000,
		description:
			'The course delivers core components of identifying, combining and analysing routinely collected health data. It covers aspects of information governance and disclosure control, as well as focus on data management, manipulation and advanced methods of data analysis. The course module is aimed at health, social and clinical researchers, who wish to learn techniques and skills to analyse linked health data. It aims to equip participants with the necessary analytical skills to analyse these types of data and to be aware of issues around clinical and information governance.',
		domains: ['Course'],
		entries: [
			{
				level: '',
				subject: '',
			},
		],
		keywords: [],
		link: 'https://www.gla.ac.uk/researchinstitutes/healthwellbeing/research/hehta/continuingprofessionaldevelopment/datascience/',
		location: 'Scotland',
		nationalPriority: '',
		provider: 'University of Glasgow',
		relatedObjects: [],
		restrictions: 'Open',
		title: 'Data Science - Identifying, combining and analysing health data sets ',
		type: 'course',
		updatedAt: '2021-02-11T17:25:22.752Z',
		persons: [],
		objects: [],
		reviews: [],
	},
	{
		_id: '602427a273d8765aeb89f886',
		id: 50034,
		activeflag: 'active',
		award: [],
		competencyFramework: '',
		counter: 2,
		courseDelivery: 'campus',
		courseOptions: [
			{
				flexibleDates: true,
				startDate: null,
				studyMode: '',
				studyDurationNumber: null,
				studyDurationMeasure: '',
				fees: [
					{
						feeDescription: '',
						feeAmount: null,
						feePer: '',
					},
				],
			},
		],
		createdAt: '2021-02-10T18:36:18.463Z',
		creator: 50000,
		description:
			'Health data analytics involves extracting insights from health data, either to shape national policy, manage local organisations or inform the care of an individual. As more and more data becomes available electronically, the demand for skilled and trained individuals to take advantage of it becomes increasingly urgent.',
		domains: ['Course'],
		entries: [
			{
				level: '',
				subject: '',
			},
		],
		keywords: [],
		link: 'https://www.ucl.ac.uk/health-informatics/study/postgraduate-taught-programmes/health-data-analytics-mscpg-dippg-cert',
		location: 'London',
		nationalPriority: '',
		provider: 'UCL Institute of Health Informatics',
		relatedObjects: [],
		restrictions: 'other:Relevant first degree or equivalent experience required',
		title: 'Health Data Analytics ',
		type: 'course',
		updatedAt: '2021-02-11T17:22:50.815Z',
		persons: [],
		objects: [],
		reviews: [],
	},
];
