export const toolsStub = [
	{
		_id: '5ece82142abda8b3a06f1a22',
		activeflag: 'active',
		id: 19008,
		type: 'tool',
		license: '',
		name: 'C19 Track',
		description: 'Help paint a more accurate picture of covid-19 in your community',
		tags: {
			features: ['Community Tracking'],
			topics: ['COVID-19'],
		},
		link: 'https://c19track.com/',
		updatedon: '2020-05-27T00:00:00.000Z',
		datasetids: [],
		categories: {
			category: 'Questionnaire',
			programmingLanguageVersion: '',
			programmingLanguage: [],
		},
		authors: [190000],
		projectids: [],
		authors_names: ['University of St. Andrews'],
		counter: 65,
		updatedAt: '2021-02-14T16:23:25.846Z',
		persons: [],
		objects: [],
		reviews: [],
	},
	{
		_id: '5ece82142abda8b3a06f1a1b',
		updatedon: '2020-05-27T00:00:00.000Z',
		datasetids: [],
		license: '',
		description: '',
		name: 'CMMID Interactive Applications',
		tags: {
			topics: ['COVID-19'],
			features: ['Modelling', 'Visualisation'],
		},
		link: 'https://cmmid.github.io/visualisations',
		activeflag: 'active',
		id: 19001,
		type: 'tool',
		authors_names: ['LSHTM'],
		projectids: [],
		authors: [190000],
		categories: {
			category: 'Data Modelling',
			programmingLanguageVersion: '',
			programmingLanguage: ['R'],
		},
		counter: 99,
		updatedAt: '2021-02-14T12:20:22.364Z',
		discourseTopicId: 13,
		programmingLanguage: [
			{
				programmingLanguage: 'R',
				version: '',
			},
		],
		persons: [],
		objects: [],
		reviews: [],
	},
	{
		_id: '5f71c7537815d0195a1e9b74',
		categories: {
			programmingLanguage: ['Java'],
			category: 'Software',
			programmingLanguageVersion: '',
		},
		tags: {
			features: ['Data Cleaning', 'Data Import/Export', 'Data Integration', 'Data Reduction', 'Data Transformation', 'Data Visualization'],
			topics: [],
		},
		datasetfields: {
			geographicCoverage: [],
			physicalSampleAvailability: [],
			technicaldetails: [],
			versionLinks: [],
			phenotypes: [],
		},
		authors: [4442271343443529],
		toolids: [],
		datasetids: [],
		relatedObjects: [],
		id: 8656803550224388,
		type: 'tool',
		name: 'DataPreparator',
		link: 'https://www.datapreparator.com/',
		description:
			'DataPreparator is a free software tool designed to assist with common tasks of  data preparation (or data preprocessing) in data analysis and data mining. \n\nDataPreparator provides:\n\n-A variety of techniques for data cleaning, transformation, and exploration\n-Chaining of preprocessing operators into a flow graph (operator tree)\n-Handling of large volumes of data (since data sets are not stored in the computer memory)\n-Stand alone tool independent of any other tools\n-User friendly graphical user interface\n\nDataPreparator can assist you with exploring and preparing data in various ways prior to data analysis or data mining. It includes operators for cleaning, discretization, numeration, scaling, attribute selection, missing values, outliers, statistics, visualization, balancing, sampling, row selection, and several other tasks. See Features for details.',
		license: 'https://www.datapreparator.com/software-license-agreement-2.html',
		activeflag: 'active',
		updatedon: '2020-09-28T11:21:55.527Z',
		uploader: 4442271343443529,
		createdAt: '2020-09-28T11:21:55.530Z',
		updatedAt: '2021-02-14T08:55:13.596Z',
		counter: 12,
		programmingLanguage: [
			{
				programmingLanguage: 'Java',
				version: '',
			},
		],
		persons: [],
		objects: [],
		reviews: [],
	},
	{
		_id: '5eda27d4aac50ef405c861fd',
		categories: {
			programmingLanguage: ['R'],
			category: 'Package',
			programmingLanguageVersion: '',
		},
		tags: {
			features: ['Imputation', 'Phenomics', 'Data management', 'Natural language processing'],
			topics: [],
		},
		authors: [19451923771745828],
		id: 22796788425888104,
		type: 'tool',
		name: 'CALIBER health records research toolkit',
		link: 'http://caliberanalysis.r-forge.r-project.org/',
		description:
			'This project comprises a set of R packages to assist in epidemiological studies using electronic health records databases.\n\nCALIBER (http://caliberresearch.org/) is led from the Farr Institute @ London. CALIBER investigators represent a collaboration between epidemiologists, clinicians, statisticians, health informaticians and computer scientists with initial funding from the Wellcome Trust and the National Institute for Health Research.\n\nThe goal of CALIBER is to provide evidence across different stages of translation, from discovery, through evaluation to implementation where electronic health records provide new scientific opportunities.\n',
		license: 'GNU General Public License (GPL)',
		activeflag: 'active',
		updatedon: '2020-06-05T11:09:08.566Z',
		createdAt: '2020-06-05T11:09:08.573Z',
		updatedAt: '2021-02-13T22:55:00.027Z',
		counter: 127,
		discourseTopicId: 30,
		programmingLanguage: [
			{
				programmingLanguage: 'R',
				version: '',
			},
		],
		persons: [],
		objects: [],
		reviews: [],
	},
];
